server:
  port: 9090

spring:
  application:
    name: ddd-lease-api
  output:
    ansi:
      enabled: ALWAYS
  modulith:
    moments:
      enable-time-machine: true
      granularity: hours
    events:
      externalization:
        enabled: false
      republish-outstanding-events-on-restart: true
  docker:
    compose:
      enabled: true
      file: compose/compose.yaml
      lifecycle-management: start_and_stop
      skip:
        in-tests: false
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: secret
      database: lease-api
      uuid-representation: standard

logging:
  level:
    org.springframework.modulith: INFO
    org.hibernate: INFO
    nl.svb.dms.ddd_lease_api: DEBUG