server:
  port: 9090

spring:
  application:
    name: ddd-lease-api
  output:
    ansi:
      enabled: ALWAYS
  modulith:
    moments:
      enable-time-machine: true
      granularity: hours
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_and_stop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  endpoint:
    modulith:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, modulith

logging:
  level:
    org.springframework.modulith: INFO
    org.springframework.data.jdbc: DEBUG
    org.hibernate: WARN
    nl.svb.dms.ddd_lease_api: DEBUG