server:
  port: 9090

spring:
  application:
    name: ddd-lease-api
  output:
    ansi:
      enabled: ALWAYS
  modulith:
    moments:
      enable-time-machine: true
      granularity: hours
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: secret
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
  endpoint:
    modulith:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, modulith

logging:
  level:
    org.springframework.modulith: DEBUG
    org.springframework.data.jdbc: DEBUG
    org.hibernate: DEBUG