services:

  mongo-service:
    image: mongo:8.0.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    command: [ "mongod", "--replSet", "rs0" ]

volumes:
  mongo-data: